### ISSUE TITLE
Some generation issues in schema's resulting in invalid specification

### ISSUE THREAD

**Issue by bbrala** [byte-it/openapi-spec-generator#4]
There are a few issues when generating data.

```yaml
          properties: 
            answer: 
              example: "0"
              title: answer
              type: boolean
```

The boolean is stored as "0" and not really cast to boolean which gives validation errors.

```yaml
            empty: 
              value: {}
```

Empty arrays seem to generate into an empty object, this is wrong most of the time.

```yaml
components: 
  responses: 
    400: 
      content: 
        application/vnd.api+json: 
```

The specification seems to want an string here instead of an int? At least when i enter it into https://stoplight.io
